# Generated by Django 2.2 on 2019-04-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=20)),
                ('secret', models.CharField(max_length=20)),
                ('server', models.IntegerField()),
                ('farm', models.IntegerField()),
                ('title', models.TextField()),
                ('is_public', models.IntegerField()),
                ('is_friend', models.IntegerField()),
                ('is_family', models.IntegerField()),
                ('ownername', models.CharField(max_length=20)),
                ('date_added', models.BigIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='id',
        ),
        migrations.AddField(
            model_name='group',
            name='group_id',
            field=models.CharField(default=None, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=60),
        ),
    ]
