# Generated by Django 2.2 on 2019-04-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20190410_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='is_family',
            new_name='isfamily',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='is_friend',
            new_name='isfriend',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='is_public',
            new_name='ispublic',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='date_added',
        ),
        migrations.AddField(
            model_name='photo',
            name='dateadded',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=models.CharField(default=None, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='photo',
            name='server',
            field=models.CharField(max_length=20),
        ),
    ]
