# Generated by Django 2.2 on 2019-04-10 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20190410_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gallery.Group'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='ownername',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
